package com.mengyirunian.entity;

import java.io.Serializable;

public class AccessUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_user.code
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_access_user.openid
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_user.id
     *
     * @return the value of t_access_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_user.id
     *
     * @param id the value for t_access_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_user.name
     *
     * @return the value of t_access_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_user.name
     *
     * @param name the value for t_access_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_user.code
     *
     * @return the value of t_access_user.code
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_user.code
     *
     * @param code the value for t_access_user.code
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_access_user.openid
     *
     * @return the value of t_access_user.openid
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_access_user.openid
     *
     * @param openid the value for t_access_user.openid
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", openid=").append(openid);
        sb.append("]");
        return sb.toString();
    }
}