package com.mengyirunian.entity;

import java.io.Serializable;

public class CityUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city_user.city_name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city_user.id
     *
     * @return the value of t_city_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city_user.id
     *
     * @param id the value for t_city_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city_user.name
     *
     * @return the value of t_city_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city_user.name
     *
     * @param name the value for t_city_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city_user.city_name
     *
     * @return the value of t_city_user.city_name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city_user.city_name
     *
     * @param cityName the value for t_city_user.city_name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", cityName=").append(cityName);
        sb.append("]");
        return sb.toString();
    }
}