package com.mengyirunian.entity;

import java.io.Serializable;

public class MarriageUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_marriage_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_marriage_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_marriage_user.marriage
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_marriage_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_marriage_user.id
     *
     * @return the value of t_marriage_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_marriage_user.id
     *
     * @param id the value for t_marriage_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_marriage_user.name
     *
     * @return the value of t_marriage_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_marriage_user.name
     *
     * @param name the value for t_marriage_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_marriage_user.marriage
     *
     * @return the value of t_marriage_user.marriage
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_marriage_user.marriage
     *
     * @param marriage the value for t_marriage_user.marriage
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_marriage_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", marriage=").append(marriage);
        sb.append("]");
        return sb.toString();
    }
}