package com.mengyirunian.entity;

import java.io.Serializable;

public class OccupationUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_occupation_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_occupation_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_occupation_user.occupation
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_occupation_user.id
     *
     * @return the value of t_occupation_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_occupation_user.id
     *
     * @param id the value for t_occupation_user.id
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_occupation_user.name
     *
     * @return the value of t_occupation_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_occupation_user.name
     *
     * @param name the value for t_occupation_user.name
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_occupation_user.occupation
     *
     * @return the value of t_occupation_user.occupation
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_occupation_user.occupation
     *
     * @param occupation the value for t_occupation_user.occupation
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", occupation=").append(occupation);
        sb.append("]");
        return sb.toString();
    }
}