package com.mengyirunian.entity;

import java.io.Serializable;
import java.util.Date;

public class Resource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.service_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.service_code
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_parent
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private String funcParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_parent_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private String funcParentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_action
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private String funcAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_action_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private String funcActionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_type
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private Integer funcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.valid
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_at
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.update_at
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.service_name
     *
     * @return the value of resource.service_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.service_name
     *
     * @param serviceName the value for resource.service_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.service_code
     *
     * @return the value of resource.service_code
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.service_code
     *
     * @param serviceCode the value for resource.service_code
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_parent
     *
     * @return the value of resource.func_parent
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public String getFuncParent() {
        return funcParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.func_parent
     *
     * @param funcParent the value for resource.func_parent
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setFuncParent(String funcParent) {
        this.funcParent = funcParent == null ? null : funcParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_parent_name
     *
     * @return the value of resource.func_parent_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public String getFuncParentName() {
        return funcParentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.func_parent_name
     *
     * @param funcParentName the value for resource.func_parent_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setFuncParentName(String funcParentName) {
        this.funcParentName = funcParentName == null ? null : funcParentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_action
     *
     * @return the value of resource.func_action
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public String getFuncAction() {
        return funcAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.func_action
     *
     * @param funcAction the value for resource.func_action
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setFuncAction(String funcAction) {
        this.funcAction = funcAction == null ? null : funcAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_action_name
     *
     * @return the value of resource.func_action_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public String getFuncActionName() {
        return funcActionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.func_action_name
     *
     * @param funcActionName the value for resource.func_action_name
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setFuncActionName(String funcActionName) {
        this.funcActionName = funcActionName == null ? null : funcActionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_type
     *
     * @return the value of resource.func_type
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public Integer getFuncType() {
        return funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.func_type
     *
     * @param funcType the value for resource.func_type
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setFuncType(Integer funcType) {
        this.funcType = funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.valid
     *
     * @return the value of resource.valid
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.valid
     *
     * @param valid the value for resource.valid
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_at
     *
     * @return the value of resource.create_at
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_at
     *
     * @param createAt the value for resource.create_at
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.update_at
     *
     * @return the value of resource.update_at
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.update_at
     *
     * @param updateAt the value for resource.update_at
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serviceName=").append(serviceName);
        sb.append(", serviceCode=").append(serviceCode);
        sb.append(", funcParent=").append(funcParent);
        sb.append(", funcParentName=").append(funcParentName);
        sb.append(", funcAction=").append(funcAction);
        sb.append(", funcActionName=").append(funcActionName);
        sb.append(", funcType=").append(funcType);
        sb.append(", valid=").append(valid);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append("]");
        return sb.toString();
    }
}