package com.mengyirunian.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResourceCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public ResourceCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFuncParentIsNull() {
            addCriterion("func_parent is null");
            return (Criteria) this;
        }

        public Criteria andFuncParentIsNotNull() {
            addCriterion("func_parent is not null");
            return (Criteria) this;
        }

        public Criteria andFuncParentEqualTo(String value) {
            addCriterion("func_parent =", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentNotEqualTo(String value) {
            addCriterion("func_parent <>", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentGreaterThan(String value) {
            addCriterion("func_parent >", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentGreaterThanOrEqualTo(String value) {
            addCriterion("func_parent >=", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentLessThan(String value) {
            addCriterion("func_parent <", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentLessThanOrEqualTo(String value) {
            addCriterion("func_parent <=", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentLike(String value) {
            addCriterion("func_parent like", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentNotLike(String value) {
            addCriterion("func_parent not like", value, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentIn(List<String> values) {
            addCriterion("func_parent in", values, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentNotIn(List<String> values) {
            addCriterion("func_parent not in", values, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentBetween(String value1, String value2) {
            addCriterion("func_parent between", value1, value2, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncParentNotBetween(String value1, String value2) {
            addCriterion("func_parent not between", value1, value2, "funcParent");
            return (Criteria) this;
        }

        public Criteria andFuncActionIsNull() {
            addCriterion("func_action is null");
            return (Criteria) this;
        }

        public Criteria andFuncActionIsNotNull() {
            addCriterion("func_action is not null");
            return (Criteria) this;
        }

        public Criteria andFuncActionEqualTo(String value) {
            addCriterion("func_action =", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionNotEqualTo(String value) {
            addCriterion("func_action <>", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionGreaterThan(String value) {
            addCriterion("func_action >", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionGreaterThanOrEqualTo(String value) {
            addCriterion("func_action >=", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionLessThan(String value) {
            addCriterion("func_action <", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionLessThanOrEqualTo(String value) {
            addCriterion("func_action <=", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionLike(String value) {
            addCriterion("func_action like", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionNotLike(String value) {
            addCriterion("func_action not like", value, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionIn(List<String> values) {
            addCriterion("func_action in", values, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionNotIn(List<String> values) {
            addCriterion("func_action not in", values, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionBetween(String value1, String value2) {
            addCriterion("func_action between", value1, value2, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncActionNotBetween(String value1, String value2) {
            addCriterion("func_action not between", value1, value2, "funcAction");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameIsNull() {
            addCriterion("func_parent_name is null");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameIsNotNull() {
            addCriterion("func_parent_name is not null");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameEqualTo(String value) {
            addCriterion("func_parent_name =", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameNotEqualTo(String value) {
            addCriterion("func_parent_name <>", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameGreaterThan(String value) {
            addCriterion("func_parent_name >", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameGreaterThanOrEqualTo(String value) {
            addCriterion("func_parent_name >=", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameLessThan(String value) {
            addCriterion("func_parent_name <", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameLessThanOrEqualTo(String value) {
            addCriterion("func_parent_name <=", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameLike(String value) {
            addCriterion("func_parent_name like", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameNotLike(String value) {
            addCriterion("func_parent_name not like", value, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameIn(List<String> values) {
            addCriterion("func_parent_name in", values, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameNotIn(List<String> values) {
            addCriterion("func_parent_name not in", values, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameBetween(String value1, String value2) {
            addCriterion("func_parent_name between", value1, value2, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncParentNameNotBetween(String value1, String value2) {
            addCriterion("func_parent_name not between", value1, value2, "funcParentName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameIsNull() {
            addCriterion("func_action_name is null");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameIsNotNull() {
            addCriterion("func_action_name is not null");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameEqualTo(String value) {
            addCriterion("func_action_name =", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameNotEqualTo(String value) {
            addCriterion("func_action_name <>", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameGreaterThan(String value) {
            addCriterion("func_action_name >", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameGreaterThanOrEqualTo(String value) {
            addCriterion("func_action_name >=", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameLessThan(String value) {
            addCriterion("func_action_name <", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameLessThanOrEqualTo(String value) {
            addCriterion("func_action_name <=", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameLike(String value) {
            addCriterion("func_action_name like", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameNotLike(String value) {
            addCriterion("func_action_name not like", value, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameIn(List<String> values) {
            addCriterion("func_action_name in", values, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameNotIn(List<String> values) {
            addCriterion("func_action_name not in", values, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameBetween(String value1, String value2) {
            addCriterion("func_action_name between", value1, value2, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andFuncActionNameNotBetween(String value1, String value2) {
            addCriterion("func_action_name not between", value1, value2, "funcActionName");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Integer value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Integer value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Integer value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Integer value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Integer value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Integer value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Integer> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Integer> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Integer value1, Integer value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Integer value1, Integer value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resource
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 12 02:20:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}