package com.mengyirunian.entity;

import java.io.Serializable;
import java.util.Date;

public class Resource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_parent
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private String funcParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_action
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private String funcAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_parent_name
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private String funcParentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.func_action_name
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private String funcActionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.valid
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_at
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.update_at
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Resource(Integer id, String funcParent, String funcAction, String funcParentName, String funcActionName, Integer valid, Date createAt, Date updateAt) {
        this.id = id;
        this.funcParent = funcParent;
        this.funcAction = funcAction;
        this.funcParentName = funcParentName;
        this.funcActionName = funcActionName;
        this.valid = valid;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_parent
     *
     * @return the value of resource.func_parent
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String getFuncParent() {
        return funcParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_action
     *
     * @return the value of resource.func_action
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String getFuncAction() {
        return funcAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_parent_name
     *
     * @return the value of resource.func_parent_name
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String getFuncParentName() {
        return funcParentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.func_action_name
     *
     * @return the value of resource.func_action_name
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String getFuncActionName() {
        return funcActionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.valid
     *
     * @return the value of resource.valid
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_at
     *
     * @return the value of resource.create_at
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.update_at
     *
     * @return the value of resource.update_at
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", funcParent=").append(funcParent);
        sb.append(", funcAction=").append(funcAction);
        sb.append(", funcParentName=").append(funcParentName);
        sb.append(", funcActionName=").append(funcActionName);
        sb.append(", valid=").append(valid);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append("]");
        return sb.toString();
    }
}