package com.mengyirunian.entity;

import java.io.Serializable;
import java.util.Date;

public class RoleResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.resource_id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.valid
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.create_at
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.update_at
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_resource
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.id
     *
     * @return the value of role_resource.id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.id
     *
     * @param id the value for role_resource.id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_id
     *
     * @return the value of role_resource.role_id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_id
     *
     * @param roleId the value for role_resource.role_id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.resource_id
     *
     * @return the value of role_resource.resource_id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.resource_id
     *
     * @param resourceId the value for role_resource.resource_id
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.valid
     *
     * @return the value of role_resource.valid
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.valid
     *
     * @param valid the value for role_resource.valid
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.create_at
     *
     * @return the value of role_resource.create_at
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.create_at
     *
     * @param createAt the value for role_resource.create_at
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.update_at
     *
     * @return the value of role_resource.update_at
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.update_at
     *
     * @param updateAt the value for role_resource.update_at
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun Jan 14 19:22:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", resourceId=").append(resourceId);
        sb.append(", valid=").append(valid);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append("]");
        return sb.toString();
    }
}