package com.mengyirunian.entity;

import java.io.Serializable;

public class WeixinInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_weixin_info.id
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_weixin_info.keyname
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    private String keyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_weixin_info.valuename
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    private String valuename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weixin_info
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_weixin_info.id
     *
     * @return the value of t_weixin_info.id
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_weixin_info.id
     *
     * @param id the value for t_weixin_info.id
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_weixin_info.keyname
     *
     * @return the value of t_weixin_info.keyname
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    public String getKeyname() {
        return keyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_weixin_info.keyname
     *
     * @param keyname the value for t_weixin_info.keyname
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    public void setKeyname(String keyname) {
        this.keyname = keyname == null ? null : keyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_weixin_info.valuename
     *
     * @return the value of t_weixin_info.valuename
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    public String getValuename() {
        return valuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_weixin_info.valuename
     *
     * @param valuename the value for t_weixin_info.valuename
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    public void setValuename(String valuename) {
        this.valuename = valuename == null ? null : valuename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Thu Mar 22 00:36:35 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", keyname=").append(keyname);
        sb.append(", valuename=").append(valuename);
        sb.append("]");
        return sb.toString();
    }
}