package com.mengyirunian.mapper;

import com.mengyirunian.entity.AccessUser;
import com.mengyirunian.entity.AccessUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AccessUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=AccessUserSqlProvider.class, method="countByExample")
    int countByExample(AccessUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @DeleteProvider(type=AccessUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(AccessUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Delete({
        "delete from t_access_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Insert({
        "insert into t_access_user (name, code, ",
        "openid)",
        "values (#{name,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{openid,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AccessUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @InsertProvider(type=AccessUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(AccessUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=AccessUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR)
    })
    List<AccessUser> selectByExampleWithRowbounds(AccessUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=AccessUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR)
    })
    List<AccessUser> selectByExample(AccessUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Select({
        "select",
        "id, name, code, openid",
        "from t_access_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR)
    })
    AccessUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=AccessUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AccessUser record, @Param("example") AccessUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=AccessUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AccessUser record, @Param("example") AccessUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=AccessUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AccessUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Update({
        "update t_access_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "openid = #{openid,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AccessUser record);
}