package com.mengyirunian.mapper;

import com.mengyirunian.entity.ChildUser;
import com.mengyirunian.entity.ChildUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface ChildUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=ChildUserSqlProvider.class, method="countByExample")
    int countByExample(ChildUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @DeleteProvider(type=ChildUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(ChildUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Delete({
        "delete from t_child_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Insert({
        "insert into t_child_user (name, child_number)",
        "values (#{name,jdbcType=VARCHAR}, #{childNumber,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ChildUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @InsertProvider(type=ChildUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ChildUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=ChildUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="child_number", property="childNumber", jdbcType=JdbcType.INTEGER)
    })
    List<ChildUser> selectByExampleWithRowbounds(ChildUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=ChildUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="child_number", property="childNumber", jdbcType=JdbcType.INTEGER)
    })
    List<ChildUser> selectByExample(ChildUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Select({
        "select",
        "id, name, child_number",
        "from t_child_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="child_number", property="childNumber", jdbcType=JdbcType.INTEGER)
    })
    ChildUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=ChildUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ChildUser record, @Param("example") ChildUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=ChildUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ChildUser record, @Param("example") ChildUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=ChildUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ChildUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_child_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Update({
        "update t_child_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "child_number = #{childNumber,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ChildUser record);
}