package com.mengyirunian.mapper;

import com.mengyirunian.entity.CityUser;
import com.mengyirunian.entity.CityUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface CityUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=CityUserSqlProvider.class, method="countByExample")
    int countByExample(CityUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @DeleteProvider(type=CityUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(CityUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Delete({
        "delete from t_city_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Insert({
        "insert into t_city_user (name, city_name)",
        "values (#{name,jdbcType=VARCHAR}, #{cityName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @InsertProvider(type=CityUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=CityUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_name", property="cityName", jdbcType=JdbcType.VARCHAR)
    })
    List<CityUser> selectByExampleWithRowbounds(CityUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=CityUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_name", property="cityName", jdbcType=JdbcType.VARCHAR)
    })
    List<CityUser> selectByExample(CityUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Select({
        "select",
        "id, name, city_name",
        "from t_city_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_name", property="cityName", jdbcType=JdbcType.VARCHAR)
    })
    CityUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=CityUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CityUser record, @Param("example") CityUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=CityUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CityUser record, @Param("example") CityUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=CityUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Update({
        "update t_city_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "city_name = #{cityName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CityUser record);
}