package com.mengyirunian.mapper;

import com.mengyirunian.entity.OccupationUser;
import com.mengyirunian.entity.OccupationUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface OccupationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=OccupationUserSqlProvider.class, method="countByExample")
    int countByExample(OccupationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @DeleteProvider(type=OccupationUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(OccupationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Delete({
        "delete from t_occupation_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Insert({
        "insert into t_occupation_user (name, occupation)",
        "values (#{name,jdbcType=VARCHAR}, #{occupation,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OccupationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @InsertProvider(type=OccupationUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(OccupationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=OccupationUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="occupation", property="occupation", jdbcType=JdbcType.VARCHAR)
    })
    List<OccupationUser> selectByExampleWithRowbounds(OccupationUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=OccupationUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="occupation", property="occupation", jdbcType=JdbcType.VARCHAR)
    })
    List<OccupationUser> selectByExample(OccupationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Select({
        "select",
        "id, name, occupation",
        "from t_occupation_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="occupation", property="occupation", jdbcType=JdbcType.VARCHAR)
    })
    OccupationUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=OccupationUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OccupationUser record, @Param("example") OccupationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=OccupationUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OccupationUser record, @Param("example") OccupationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=OccupationUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OccupationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupation_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Update({
        "update t_occupation_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "occupation = #{occupation,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OccupationUser record);
}