package com.mengyirunian.mapper;

import com.mengyirunian.entity.Resource;
import com.mengyirunian.entity.ResourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @SelectProvider(type=ResourceSqlProvider.class, method="countByExample")
    int countByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @DeleteProvider(type=ResourceSqlProvider.class, method="deleteByExample")
    int deleteByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @Delete({
        "delete from resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @Insert({
        "insert into resource (service_name, service_code, ",
        "func_parent, func_parent_name, ",
        "func_action, func_action_name, ",
        "func_type, valid, ",
        "create_at, update_at)",
        "values (#{serviceName,jdbcType=VARCHAR}, #{serviceCode,jdbcType=VARCHAR}, ",
        "#{funcParent,jdbcType=VARCHAR}, #{funcParentName,jdbcType=VARCHAR}, ",
        "#{funcAction,jdbcType=VARCHAR}, #{funcActionName,jdbcType=VARCHAR}, ",
        "#{funcType,jdbcType=INTEGER}, #{valid,jdbcType=INTEGER}, ",
        "#{createAt,jdbcType=TIMESTAMP}, #{updateAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @InsertProvider(type=ResourceSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @SelectProvider(type=ResourceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="service_name", property="serviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_code", property="serviceCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_parent", property="funcParent", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_parent_name", property="funcParentName", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_action", property="funcAction", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_action_name", property="funcActionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_type", property="funcType", jdbcType=JdbcType.INTEGER),
        @Result(column="valid", property="valid", jdbcType=JdbcType.INTEGER),
        @Result(column="create_at", property="createAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_at", property="updateAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Resource> selectByExampleWithRowbounds(ResourceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @SelectProvider(type=ResourceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="service_name", property="serviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_code", property="serviceCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_parent", property="funcParent", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_parent_name", property="funcParentName", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_action", property="funcAction", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_action_name", property="funcActionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_type", property="funcType", jdbcType=JdbcType.INTEGER),
        @Result(column="valid", property="valid", jdbcType=JdbcType.INTEGER),
        @Result(column="create_at", property="createAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_at", property="updateAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Resource> selectByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @Select({
        "select",
        "id, service_name, service_code, func_parent, func_parent_name, func_action, ",
        "func_action_name, func_type, valid, create_at, update_at",
        "from resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="service_name", property="serviceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_code", property="serviceCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_parent", property="funcParent", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_parent_name", property="funcParentName", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_action", property="funcAction", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_action_name", property="funcActionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="func_type", property="funcType", jdbcType=JdbcType.INTEGER),
        @Result(column="valid", property="valid", jdbcType=JdbcType.INTEGER),
        @Result(column="create_at", property="createAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_at", property="updateAt", jdbcType=JdbcType.TIMESTAMP)
    })
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @UpdateProvider(type=ResourceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @UpdateProvider(type=ResourceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @UpdateProvider(type=ResourceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Jan 14 17:13:18 CST 2018
     */
    @Update({
        "update resource",
        "set service_name = #{serviceName,jdbcType=VARCHAR},",
          "service_code = #{serviceCode,jdbcType=VARCHAR},",
          "func_parent = #{funcParent,jdbcType=VARCHAR},",
          "func_parent_name = #{funcParentName,jdbcType=VARCHAR},",
          "func_action = #{funcAction,jdbcType=VARCHAR},",
          "func_action_name = #{funcActionName,jdbcType=VARCHAR},",
          "func_type = #{funcType,jdbcType=INTEGER},",
          "valid = #{valid,jdbcType=INTEGER},",
          "create_at = #{createAt,jdbcType=TIMESTAMP},",
          "update_at = #{updateAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Resource record);
}