package com.mengyirunian.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.mengyirunian.entity.Resource;
import com.mengyirunian.entity.ResourceCriteria.Criteria;
import com.mengyirunian.entity.ResourceCriteria.Criterion;
import com.mengyirunian.entity.ResourceCriteria;
import java.util.List;
import java.util.Map;

public class ResourceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String countByExample(ResourceCriteria example) {
        BEGIN();
        SELECT("count(*)");
        FROM("resource");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String deleteByExample(ResourceCriteria example) {
        BEGIN();
        DELETE_FROM("resource");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String insertSelective(Resource record) {
        BEGIN();
        INSERT_INTO("resource");
        
        if (record.getFuncParent() != null) {
            VALUES("func_parent", "#{funcParent,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncAction() != null) {
            VALUES("func_action", "#{funcAction,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncParentName() != null) {
            VALUES("func_parent_name", "#{funcParentName,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncActionName() != null) {
            VALUES("func_action_name", "#{funcActionName,jdbcType=VARCHAR}");
        }
        
        if (record.getValid() != null) {
            VALUES("valid", "#{valid,jdbcType=INTEGER}");
        }
        
        if (record.getCreateAt() != null) {
            VALUES("create_at", "#{createAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAt() != null) {
            VALUES("update_at", "#{updateAt,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String selectByExample(ResourceCriteria example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("func_parent");
        SELECT("func_action");
        SELECT("func_parent_name");
        SELECT("func_action_name");
        SELECT("valid");
        SELECT("create_at");
        SELECT("update_at");
        FROM("resource");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Resource record = (Resource) parameter.get("record");
        ResourceCriteria example = (ResourceCriteria) parameter.get("example");
        
        BEGIN();
        UPDATE("resource");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getFuncParent() != null) {
            SET("func_parent = #{record.funcParent,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncAction() != null) {
            SET("func_action = #{record.funcAction,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncParentName() != null) {
            SET("func_parent_name = #{record.funcParentName,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncActionName() != null) {
            SET("func_action_name = #{record.funcActionName,jdbcType=VARCHAR}");
        }
        
        if (record.getValid() != null) {
            SET("valid = #{record.valid,jdbcType=INTEGER}");
        }
        
        if (record.getCreateAt() != null) {
            SET("create_at = #{record.createAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAt() != null) {
            SET("update_at = #{record.updateAt,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("resource");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("func_parent = #{record.funcParent,jdbcType=VARCHAR}");
        SET("func_action = #{record.funcAction,jdbcType=VARCHAR}");
        SET("func_parent_name = #{record.funcParentName,jdbcType=VARCHAR}");
        SET("func_action_name = #{record.funcActionName,jdbcType=VARCHAR}");
        SET("valid = #{record.valid,jdbcType=INTEGER}");
        SET("create_at = #{record.createAt,jdbcType=TIMESTAMP}");
        SET("update_at = #{record.updateAt,jdbcType=TIMESTAMP}");
        
        ResourceCriteria example = (ResourceCriteria) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    public String updateByPrimaryKeySelective(Resource record) {
        BEGIN();
        UPDATE("resource");
        
        if (record.getFuncParent() != null) {
            SET("func_parent = #{funcParent,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncAction() != null) {
            SET("func_action = #{funcAction,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncParentName() != null) {
            SET("func_parent_name = #{funcParentName,jdbcType=VARCHAR}");
        }
        
        if (record.getFuncActionName() != null) {
            SET("func_action_name = #{funcActionName,jdbcType=VARCHAR}");
        }
        
        if (record.getValid() != null) {
            SET("valid = #{valid,jdbcType=INTEGER}");
        }
        
        if (record.getCreateAt() != null) {
            SET("create_at = #{createAt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAt() != null) {
            SET("update_at = #{updateAt,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri Jan 12 02:20:54 CST 2018
     */
    protected void applyWhere(ResourceCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}