package com.mengyirunian.mapper;

import com.mengyirunian.entity.SalaryUser;
import com.mengyirunian.entity.SalaryUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface SalaryUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=SalaryUserSqlProvider.class, method="countByExample")
    int countByExample(SalaryUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @DeleteProvider(type=SalaryUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(SalaryUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Delete({
        "delete from t_salary_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Insert({
        "insert into t_salary_user (name, salary)",
        "values (#{name,jdbcType=VARCHAR}, #{salary,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SalaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @InsertProvider(type=SalaryUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SalaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=SalaryUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.INTEGER)
    })
    List<SalaryUser> selectByExampleWithRowbounds(SalaryUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @SelectProvider(type=SalaryUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.INTEGER)
    })
    List<SalaryUser> selectByExample(SalaryUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Select({
        "select",
        "id, name, salary",
        "from t_salary_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.INTEGER)
    })
    SalaryUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=SalaryUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SalaryUser record, @Param("example") SalaryUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=SalaryUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SalaryUser record, @Param("example") SalaryUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @UpdateProvider(type=SalaryUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SalaryUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_user
     *
     * @mbggenerated Tue Mar 20 13:01:41 CST 2018
     */
    @Update({
        "update t_salary_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "salary = #{salary,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SalaryUser record);
}